create schema album;
create table album.ALBUM (
	ALBUM_ID VARCHAR(11) NOT NULL,
	USER_ID VARCHAR(11) NOT NULL,
	TITLE VARCHAR(100) NOT NULL,
	CREATED_TIME		BIGINT NOT NULL,
	UPDATED_TIME		BIGINT NOT NULL,
	
	PRIMARY KEY (ALBUM_ID)
);

create table album.PHOTO (
	PHOTO_ID VARCHAR(11) NOT NULL,
	ALBUM_ID VARCHAR(11) NOT NULL,
	TITLE VARCHAR(100) NOT NULL,
	URL   VARCHAR(100) NOT NULL,
	CREATED_TIME		BIGINT NOT NULL,
	UPDATED_TIME		BIGINT NOT NULL,
	
	PRIMARY KEY (PHOTO_ID),
	FOREIGN KEY (ALBUM_ID) REFERENCES album.ALBUM(ALBUM_ID)
);

CREATE SEQUENCE album.ALBUM_SEQUENCE START WITH 1 INCREMENT BY 1
CREATE SEQUENCE album.PHOTO_SEQUENCE START WITH 1 INCREMENT BY 1



